In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3

df_games = pd.read_csv("C:/Users/esteb/Documents/Esteban/CURSOS/Data-analisis-ComIT_ok/proyecto-final-data-analysis/data/steam_games_clean.csv")
df_reviews = pd.read_csv("C:/Users/esteb/Documents/Esteban/CURSOS/Data-analisis-ComIT_ok/proyecto-final-data-analysis/data/steam_games_reviews.csv")

In [5]:
df_games.estimated_owners.value_counts()

estimated_owners
20000 - 50000            11258
50000 - 100000            5290
100000 - 200000           3402
200000 - 500000           2801
500000 - 1000000          1124
1000000 - 2000000          704
2000000 - 5000000          393
5000000 - 10000000         119
10000000 - 20000000         49
20000000 - 50000000         29
50000000 - 100000000         7
100000000 - 200000000        4
Name: count, dtype: int64

In [36]:
#Se hace una copia del DB para ajustar la óptica de los registros más relevantes para el análisis de los juegos más exitosos. Se tomarán los registros con mas de 1.000.000 ventas, significando aproximadamente la mitad de la escala de la que se tienen registros.

df_games1 = df_games.copy()

df_games1["estimated_owners"] = df_games.estimated_owners[df_games1.estimated_owners.isin(["1000000 - 2000000", "2000000 - 5000000", "5000000 - 10000000", "10000000 - 20000000", "20000000 - 50000000", "50000000 - 100000000", "100000000 - 200000000"])]

df_games1 = df_games1.dropna(subset=["estimated_owners"])

df_games1.head(20)

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,tags,positive,negative,average_playtime_forever,median_playtime_forever,short_description,dlc_count,new_app_id
26,879160,Battlerite Royale,2019-02-19,0.00,free,1000000 - 2000000,"[""Stunlock Studios""]","[""Stunlock Studios""]","[""Action"", ""Free To Play"", ""Massively Multipla...","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""Battle Royale"", ""Free to Play"", ""Multiplayer...",6088,2103,529,115,Explore the fantastical Talon Island in a thri...,3,27
38,880940,Pummel Party,2018-09-20,14.99,paid,2000000 - 5000000,"[""Rebuilt Games""]","[""Rebuilt Games""]","[""Action"", ""Casual"", ""Indie""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""Multiplayer"", ""Funny"", ""Online Co-Op"", ""4 Pl...",47800,6014,872,429,Pummel Party is a 4-8 player online and local-...,0,39
40,881020,Granblue Fantasy: Relink,2024-01-31,59.99,paid,2000000 - 5000000,"[""Cygames, Inc.""]","[""Cygames, Inc.""]","[""Action"", ""Adventure"", ""RPG""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...","[""Anime"", ""JRPG"", ""Action RPG"", ""Action"", ""Onl...",43116,4883,3506,1788,A grand adventure in the skies awaits! Form a ...,25,41
41,881100,Noita,2020-10-15,19.99,paid,2000000 - 5000000,"[""Nolla Games""]","[""Nolla Games""]","[""Action"", ""Adventure"", ""Indie"", ""RPG"", ""Simul...","[""Single-player"", ""Steam Achievements"", ""Steam...","[""Physics"", ""Rogue-like"", ""Pixel Graphics"", ""D...",74759,3718,2075,350,Noita is a magical action roguelite set in a w...,1,42
52,882100,XCOM®: Chimera Squad,2020-04-23,9.99,paid,1000000 - 2000000,"[""Firaxis Games""]","[""2K""]","[""Strategy""]","[""Single-player"", ""Steam Achievements"", ""Steam...","[""Strategy"", ""Turn-Based Tactics"", ""Turn-Based...",16302,6407,1095,608,XCOM: Chimera Squad delivers an all-new story ...,0,53
79,883710,Resident Evil 2,2019-01-24,49.99,paid,5000000 - 10000000,"[""CAPCOM Co., Ltd.""]","[""CAPCOM Co., Ltd.""]","[""Action""]","[""Single-player"", ""Steam Achievements"", ""Full ...","[""Zombies"", ""Survival Horror"", ""Horror"", ""Sing...",167647,5210,1254,792,A deadly virus engulfs the residents of Raccoo...,13,80
89,884660,CRSED: Cuisine Royale,2018-06-15,0.00,free,2000000 - 5000000,"[""Darkflow Software"", ""Matter Team""]","[""Gaijin Network Ltd""]","[""Action"", ""Massively Multiplayer"", ""Free To P...","[""Single-player"", ""Multi-player"", ""MMO"", ""PvP""...","[""Battle Royale"", ""Free to Play"", ""Multiplayer...",30411,8179,682,56,CRSED: Cuisine Royale – is a brutal MMO last-m...,0,90
168,892970,Valheim,2021-02-02,19.99,paid,10000000 - 20000000,"[""Iron Gate AB""]","[""Coffee Stain Publishing""]","[""Action"", ""Adventure"", ""Indie"", ""RPG"", ""Early...","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...","[""Open World Survival Craft"", ""Survival"", ""Onl...",471451,28377,4294,1693,A brutal exploration and survival game for 1-1...,1,169
242,899440,GOD EATER 3,2019-02-07,59.99,paid,1000000 - 2000000,"[""BANDAI NAMCO Studios Inc.""]","[""BANDAI NAMCO Entertainment""]","[""Action""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""Anime"", ""Action"", ""Character Customization"",...",7450,1921,969,549,"Set in a post-apocalyptic setting, it’s up to ...",0,243
244,899770,Last Epoch,2024-02-21,34.99,paid,20000000 - 50000000,"[""Eleventh Hour Games""]","[""Eleventh Hour Games""]","[""Action"", ""Adventure"", ""Indie"", ""RPG""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...","[""Action RPG"", ""Loot"", ""Hack and Slash"", ""RPG""...",88027,22596,4749,2613,"Uncover the Past, Reforge the Future. Ascend i...",8,245
255,903950,Last Oasis,2020-03-26,29.99,paid,1000000 - 2000000,"[""Donkey Crew""]","[""Donkey Crew"", ""Snail Games USA""]","[""Action"", ""Adventure"", ""Indie"", ""Massively Mu...","[""Multi-player"", ""MMO"", ""PvP"", ""Online PvP"", ""...","[""Massively Multiplayer"", ""Survival"", ""Open Wo...",14952,9133,6373,1762,Nomadic Survival MMO. Build wooden walking mac...,1,256
320,911400,Assassin's Creed® III Remastered,2019-03-29,39.99,paid,1000000 - 2000000,"[""Ubisoft Entertainment""]","[""Ubisoft Entertainment""]","[""Action"", ""Adventure""]","[""Single-player"", ""Partial Controller Support""]","[""Action"", ""Adventure"", ""Assassin"", ""Open Worl...",7703,4881,771,200,Relive the American Revolution or experience i...,0,321
356,915320,Pixel Strike 3D,2020-05-29,0.00,free,1000000 - 2000000,"[""Vulcron""]","[""Vulcron""]","[""Action"", ""Adventure"", ""Indie"", ""RPG"", ""Free ...","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""Free to Play"", ""FPS"", ""Tactical"", ""Multiplay...",9310,3293,181,67,Pixel Strike 3D is a Multiplayer First-Person ...,0,357
368,916440,Anno 1800,2019-04-16,59.99,paid,1000000 - 2000000,"[""Ubisoft Mainz""]","[""Ubisoft""]","[""Simulation"", ""Strategy""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""City Builder"", ""Strategy"", ""Simulation"", ""Ec...",20368,4723,2458,808,Anno 1800™ – Lead the Industrial Revolution! W...,35,369
383,918570,Century: Age of Ashes,2021-12-02,0.00,free,2000000 - 5000000,"[""Playwing LTD""]","[""Playwing LTD""]","[""Action"", ""Indie"", ""Racing"", ""Free To Play""]","[""Multi-player"", ""PvP"", ""Online PvP"", ""Co-op"",...","[""Free to Play"", ""Dragons"", ""Multiplayer"", ""Ac...",13226,4514,144,54,Century: Age of Ashes is a free-to-play multip...,17,384
394,920210,LEGO® Star Wars™: The Skywalker Saga,2022-04-05,69.99,paid,1000000 - 2000000,"[""TT Games""]","[""Warner Bros. Games"", ""Warner Bros. Interacti...","[""Action"", ""Adventure""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""Sh...","[""LEGO"", ""Adventure"", ""Co-op"", ""Multiplayer"", ...",40865,4173,1391,604,Play through all nine Skywalker saga films in ...,16,395
441,924970,Back 4 Blood,2021-10-12,59.99,paid,1000000 - 2000000,"[""Turtle Rock Studios""]","[""Warner Bros. Games""]","[""Action""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""Zombies"", ""Online Co-Op"", ""Multiplayer"", ""FP...",46833,21608,1816,543,Back 4 Blood is a thrilling cooperative first-...,4,442
497,931690,Himno,2019-04-26,0.00,free,1000000 - 2000000,"[""David Moralejo Sánchez""]","[""GrabTheGames"", ""UpgradePoint""]","[""Adventure"", ""Casual"", ""Indie"", ""Free To Play""]","[""Single-player"", ""Steam Achievements"", ""Parti...","[""Free to Play"", ""Pixel Graphics"", ""2D"", ""Plat...",5272,503,36,18,"Himno is a peaceful, 2D platformer game with a...",1,498
507,933110,Age of Empires III: Definitive Edition,2020-10-15,0.00,free,1000000 - 2000000,"[""World's Edge"", ""Tantalus Media"", ""Forgotten ...","[""Xbox Game Studios""]","[""Strategy"", ""Free To Play""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...","[""Strategy"", ""Base-Building"", ""RTS"", ""Multipla...",40941,7401,1799,291,Age of Empires III: Definitive Edition offers ...,9,508
564,939400,LoveChoice,2021-11-15,1.99,paid,1000000 - 2000000,"[""Akaba Studio""]","[""Akaba Studio""]","[""Adventure"", ""Indie"", ""RPG"", ""Simulation""]","[""Single-player"", ""Steam Achievements"", ""Steam...","[""Romance"", ""Dating Sim"", ""Choices Matter"", ""S...",31465,2425,158,86,'What is love?' We try to answer that with thi...,3,565

In [44]:
#Creación de columnas de total rating y balance de rating.

df_games1["total_ratings"] = df_games1["positive"] + df_games1["negative"]

df_games1["rating_balance"] = (((df_games1["positive"] - df_games1["negative"]) / df_games1["total_ratings"]) * 100).round(2)

In [49]:
#Catalogación por numero de ventas.

best_sellers = df_games1[df_games1.estimated_owners.isin(["10000000 - 20000000", "20000000 - 50000000", "50000000 - 100000000", "100000000 - 200000000", "50000000 - 100000000"])]

best_seller1 = df_games1[df_games1.estimated_owners == "100000000 - 200000000"]

best_seller2 = df_games1[df_games1.estimated_owners == "50000000 - 100000000"]

In [67]:
#Filtrado de los juegos más vendidos en relación al balance de puntuaciones de usuarios.

loved_best_sellers = best_sellers[best_sellers.rating_balance >= 90].sort_values(by="rating_balance", ascending=False)

loved_best_sellers.head()

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,tags,positive,negative,average_playtime_forever,median_playtime_forever,short_description,dlc_count,new_app_id,total_ratings,rating_balance
24773,400,Portal,2007-10-10,9.99,paid,10000000 - 20000000,"[""Valve""]","[""Valve""]","[{""id"": ""1"", ""description"": ""Action""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...","{""Puzzle"": 4271, ""Puzzle-Platformer"": 3219, ""F...",175024,2717,0,0,Portal™ is a new single player game from Valve...,2,24774,177741,96.94
19349,413150,Stardew Valley,2016-02-26,14.99,paid,20000000 - 50000000,"[""ConcernedApe""]","[""ConcernedApe""]","[{""id"": ""23"", ""description"": ""Indie""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...","{""Farming Sim"": 7935, ""Pixel Graphics"": 7389, ...",872384,13811,0,0,You've inherited your grandfather's old farm p...,1,19350,886195,96.88
13197,3164500,Schedule I,2025-03-24,19.99,paid,10000000 - 20000000,"[""TVGS""]","[""TVGS""]","[""Action"", ""Indie"", ""Simulation"", ""Strategy"", ...","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...","[""Simulation"", ""Co-op"", ""Crime"", ""Multiplayer""...",200803,3238,1600,1124,From small-time dope pusher to kingpin - manuf...,0,13198,204041,96.83
18734,431960,Wallpaper Engine,2018-11-16,4.99,paid,20000000 - 50000000,"[""Wallpaper Engine Team""]","[""Wallpaper Engine Team""]","[{""id"": ""4"", ""description"": ""Casual""}, {""id"": ...","[{""id"": 22, ""description"": ""Steam Achievements...","{""Mature"": 3947, ""Utilities"": 2610, ""Anime"": 2...",876898,17560,0,0,Use stunning live wallpapers on your desktop. ...,1,18735,894458,96.07
24769,220,Half-Life 2,2004-11-16,9.99,paid,10000000 - 20000000,"[""Valve""]","[""Valve""]","[{""id"": ""1"", ""description"": ""Action""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...","{""FPS"": 4270, ""Action"": 3048, ""Sci-fi"": 2695, ...",239721,5906,0,0,Reawakened from stasis in the occupied metropo...,1,24770,245627,95.19

In [71]:
best_seller1["tags"].value_counts().head(10)

tags
["Free to Play", "Battle Royale", "Multiplayer", "FPS", "Shooter", "First-Person", "PvP", "Action", "Hero Shooter", "Team-Based", "Tactical", "Sci-fi", "Loot", "Survival", "Co-op", "Character Customization", "Funny", "Lore-Rich", "Cyberpunk", "Cinematic"]                                                                                                                                            1
{"Survival": 14893, "Shooter": 12788, "Battle Royale": 10936, "Multiplayer": 10884, "FPS": 8483, "PvP": 7734, "Third-Person Shooter": 7341, "Action": 6044, "Online Co-Op": 5400, "Tactical": 5080, "Co-op": 4364, "First-Person": 4116, "Strategy": 3138, "Early Access": 2840, "Competitive": 2461, "Third Person": 2385, "Team-Based": 2108, "Difficult": 1766, "Simulation": 1411, "Stealth": 1310}    1
{"Free to Play": 60040, "MOBA": 20225, "Multiplayer": 15411, "Strategy": 14289, "e-sports": 11816, "Team-Based": 10989, "Competitive": 8324, "Action": 7939, "Online Co-Op": 7495, "PvP": 6073, "Difficult": 5376, "Co-op": 4338, "RTS": 4127, "RPG": 3807, "Tower Defense": 3796, "Fantasy": 3764, "Character Customization": 2944, "Replay Value": 2766, "Action RPG": 2471, "Simulation": 1987}         1
{"FPS": 91172, "Shooter": 65634, "Multiplayer": 62536, "Competitive": 53536, "Action": 47634, "Team-Based": 46549, "e-sports": 43682, "Tactical": 41468, "First-Person": 39540, "PvP": 34587, "Online Co-Op": 34056, "Co-op": 30342, "Strategy": 30189, "Military": 28762, "War": 28060, "Difficult": 26037, "Trading": 25813, "Realistic": 25497, "Fast-Paced": 25369, "Moddable": 6667}                  1
Name: count, dtype: int64

In [69]:
#Normalización de datos de la comlumna Tags. Actualmente tiene por cada tag asignado un numero. Se eliminan los caracteres que no nos interesan y separamos los términos clave con str.split.
df_games1["tags"] = df_games1["tags"].str.replace("0", "").str.replace("1", "").str.replace("2", "").str.replace("3", "").str.replace("4", "").str.replace("5", "").str.replace("6", "").str.replace("7", "").str.replace("8", "").str.replace("9", "").str.replace(":", "")
df_games1["tags"] = df_games1["tags"].str.split(",")

df_games1["categories"] = df_games1["categories"].str.replace("0", "").str.replace("1", "").str.replace("2", "").str.replace("3", "").str.replace("4", "").str.replace("5", "").str.replace("6", "").str.replace("7", "").str.replace("8", "").str.replace("9", "")
df_games1["categories"] = df_games1["categories"].str.split(":")


df_games1["genres"] = df_games1["genres"].str.replace("0", "").str.replace("1", "").str.replace("2", "").str.replace("3", "").str.replace("4", "").str.replace("5", "").str.replace("6", "").str.replace("7", "").str.replace("8", "").str.replace("9", "")
df_games1["genres"] = df_games1["genres"].str.split(":")

AttributeError: Can only use .str accessor with string values, not floating

In [74]:

df_games["tags"] = df_games["tags"].astype(str)

df_games1["tags"].dtype

dtype('O')